@startuml test

hide method
hide member

class Computer 
class Cpu
class MainBoard
class Memory
class PowerSupply

Cpu "1..*" --o Computer
MainBoard --o Computer
Memory "2,4" --o Computer
PowerSupply --o Computer


@enduml